name: Node Setup

on: 
      push:
            branches: [main]
jobs:
      setup-node:
            runs-on: ubuntu-latest

            defaults:
                run:
                      working-directory: backend
            steps:
                  - name: Checkout repo
                    uses: actions/checkout@v4

                  - name: setup node
                    uses: actions/setup-node@v4
